swagger: "2.0"
info:
  description: "A simple Hello world."
  title: "Endpoints - Hello World"
  version: "1.0.0"

basePath: "/"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  "/hello":
    get:
      description: "Returns the hello world"
      operationId: "say-hello"
      produces:
        - "application/json"
      responses:
        200:
          description: "hello world info."
          schema:
            $ref: "#/definitions/hello-response"
definitions:
  hello-response:
    properties:
      hello:
        type: "string"
